services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - "4000:8080"
    networks:
      - oidanice-network
    restart: unless-stopped

  app:
    image: ll4nc33/oidanice-perplexica:master
    container_name: oidanice-perplexica
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexica
    ports:
      - "3000:3000"
    networks:
      - oidanice-network
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    restart: unless-stopped
    depends_on:
      - searxng

networks:
  oidanice-network:

volumes:
  backend-dbstore:
  uploads:
